import { InputData } from './types'
import { toSlug } from './utils'
import bcrypt from 'bcryptjs'

const inputData: InputData = {
  users: [
    {
      name: 'webstoryboy',
      password: bcrypt.hashSync('123456', 10),
      email: 'webstoryboy@naver.com',
      emailVerified: false,
      image: '/face/face01.jpg',
      role: 'Admin',
      visitCount: 0,
    },
    {
      name: 'Jane Smith',
      password: bcrypt.hashSync('123456', 10),
      email: 'janesmith@example.com',
      emailVerified: false,
      image: '/face/face02.jpg',
      role: 'User',
      visitCount: 0,
    },
    {
      name: 'Alice Johnson',
      password: bcrypt.hashSync('123456', 10),
      email: 'alicej@example.com',
      emailVerified: false,
      image: '/face/face03.jpg',
      role: 'User',
      visitCount: 0,
    },
    {
      name: 'Bob Williams',
      password: bcrypt.hashSync('123456', 10),
      email: 'bobw@example.com',
      emailVerified: false,
      image: '/face/face04.jpg',
      role: 'User',
      visitCount: 0,
    },
    {
      name: 'Charlie Brown',
      password: bcrypt.hashSync('123456', 10),
      email: 'charlieb@example.com',
      emailVerified: false,
      image: '/face/face05.jpg',
      role: 'User',
      visitCount: 0,
    },
    {
      name: 'David Clark',
      password: bcrypt.hashSync('123456', 10),
      email: 'davidc@example.com',
      emailVerified: false,
      image: '/face/face06.jpg',
      role: 'User',
      visitCount: 0,
    },
    {
      name: 'Emma White',
      password: bcrypt.hashSync('123456', 10),
      email: 'emmaw@example.com',
      emailVerified: false,
      image: '/face/face07.jpg',
      role: 'User',
      visitCount: 0,
    },
    {
      name: 'Frank Green',
      password: bcrypt.hashSync('123456', 10),
      email: 'frankg@example.com',
      emailVerified: true,
      image: '/face/face08.jpg',
      role: 'User',
      visitCount: 0,
    },
    {
      name: 'Grace Hall',
      password: bcrypt.hashSync('123456', 10),
      email: 'graceh@example.com',
      emailVerified: false,
      image: '/face/face09.jpg',
      role: 'User',
      visitCount: 0,
    },
    {
      name: 'Henry Young',
      password: bcrypt.hashSync('123456', 10),
      email: 'henryy@example.com',
      emailVerified: false,
      image: '/face/face10.jpg',
      role: 'User',
      visitCount: 0,
    },
    {
      name: 'Isabella Lee',
      password: bcrypt.hashSync('123456', 10),
      email: 'isabellal@example.com',
      emailVerified: false,
      image: '/face/face03.jpg',
      role: 'User',
      visitCount: 0,
    },
    {
      name: 'Jack Wilson',
      password: bcrypt.hashSync('123456', 10),
      email: 'jackw@example.com',
      emailVerified: false,
      image: '/face/face05.jpg',
      role: 'User',
      visitCount: 0,
    },
  ],
  posts: [
    {
      title: '웹디자인개발기능사 레이아웃 유형(A-1)',
      slug: toSlug('webdesign2025 A1'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign01',
      images: 'webdesign01.jpg',
      youtubeId: 'WLHCPwqHzzQ&t=1126s',
      tags: ['webdesign', 'layout'],
      description: '웹디자인개발기능사 레이아웃 A유형 연습 강의입니다.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(A-2)',
      slug: toSlug('webdesign layout A2'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign02',
      images: 'webdesign02.jpg',
      youtubeId: 'WLHCPwqHzzQ&t=1126s',
      tags: ['webdesign', 'layout'],
      description: '웹디자인개발기능사 레이아웃 A유형 연습 강의입니다.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(A-3)',
      slug: toSlug('webdesign layout A3'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign03',
      images: 'webdesign03.jpg',
      youtubeId: 'WLHCPwqHzzQ&t=1126s',
      tags: ['webdesign', 'layout'],
      description: '웹디자인개발기능사 레이아웃 A유형 연습 강의입니다.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(A-4)',
      slug: toSlug('webdesign layout A4'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign04',
      images: 'webdesign04.jpg',
      youtubeId: 'WLHCPwqHzzQ&t=1126s',
      tags: ['webdesign', 'layout'],
      description: '웹디자인개발기능사 레이아웃 A유형 연습 강의입니다.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(B-1)',
      slug: toSlug('webdesign layout B1'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign05',
      images: 'webdesign05.jpg',
      youtubeId: 'WLHCPwqHzzQ&t=1126s',
      tags: ['webdesign', 'layout'],
      description: '웹디자인개발기능사 레이아웃 B유형 연습 강의입니다.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(B-2)',
      slug: toSlug('webdesign layout B2'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign06',
      images: 'webdesign06.jpg',
      youtubeId: 'WLHCPwqHzzQ&t=1126s',
      tags: ['webdesign', 'layout'],
      description: '웹디자인개발기능사 레이아웃 B유형 연습 강의입니다.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(B-3)',
      slug: toSlug('webdesign layout B3'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign07',
      images: 'webdesign07.jpg',
      youtubeId: 'WLHCPwqHzzQ&t=1126s',
      tags: ['webdesign', 'layout'],
      description: '웹디자인개발기능사 레이아웃 B유형 연습 강의입니다.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(B-4)',
      slug: toSlug('webdesign layout B4'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign08',
      images: 'webdesign08.jpg',
      youtubeId: 'WLHCPwqHzzQ&t=1126s',
      tags: ['webdesign', 'layout'],
      description: '웹디자인개발기능사 레이아웃 B유형 연습 강의입니다.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(C-1)',
      slug: toSlug('webdesign layout C1'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign09',
      images: 'webdesign09.jpg',
      youtubeId: 'WLHCPwqHzzQ&t=1126s',
      tags: ['webdesign', 'layout'],
      description: '웹디자인개발기능사 레이아웃 C유형 연습 강의입니다.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(C-2)',
      slug: toSlug('webdesign layout C2'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign10',
      images: 'webdesign10.jpg',
      youtubeId: 'WLHCPwqHzzQ&t=1126s',
      tags: ['webdesign', 'layout'],
      description: '웹디자인개발기능사 레이아웃 C유형 연습 강의입니다.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(C-3)',
      slug: toSlug('webdesign layout C3'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign11',
      images: 'webdesign11.jpg',
      youtubeId: 'WLHCPwqHzzQ&t=1126s',
      tags: ['webdesign', 'layout'],
      description: '웹디자인개발기능사 레이아웃 C유형 연습 강의입니다.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(C-4)',
      slug: toSlug('webdesign layout C4'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign12',
      images: 'webdesign12.jpg',
      youtubeId: 'WLHCPwqHzzQ&t=1126s',
      tags: ['webdesign', 'layout'],
      description: '웹디자인개발기능사 레이아웃 C유형 연습 강의입니다.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
    },

    {
      title: '리액트를 위한, 자바스크립트 기초 클래스 - 데이터 저장하기:변수',
      slug: toSlug('react javascript class1'),
      category: 'lecture',
      subCategory: 'javascript-react',
      components: 'javascript01',
      images: 'javascript01.jpg',
      youtubeId: 'WLHCPwqHzzQ&t=1126s',
      tags: ['javascript'],
      description:
        '리액트를 위한, 자바스크립트 기초 클래스 데이터 저장하기 파트입니다.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
    },
    {
      title: '리액트를 위한, 자바스크립트 기초 클래스 - 데이터 저장하기:배열',
      slug: toSlug('react javascript class2'),
      category: 'lecture',
      subCategory: 'javascript-react',
      components: 'javascript02',
      images: 'javascript02.jpg',
      youtubeId: 'WLHCPwqHzzQ&t=1126s',
      tags: ['javascript'],
      description:
        '리액트를 위한, 자바스크립트 기초 클래스 데이터 저장하기 파트입니다.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
    },
    {
      title: '리액트를 위한, 자바스크립트 기초 클래스 - 데이터 저장하기:객체',
      slug: toSlug('react javascript class3'),
      category: 'lecture',
      subCategory: 'javascript-react',
      components: 'javascript03',
      images: 'javascript03.jpg',
      youtubeId: '',
      tags: ['javascript'],
      description:
        '리액트를 위한, 자바스크립트 기초 클래스 데이터 저장하기 파트입니다.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
    },
    {
      title: '리액트를 위한, 자바스크립트 기초 클래스 - 데이터 저장하기:객체',
      slug: toSlug('react javascript class4'),
      category: 'lecture',
      subCategory: 'javascript-react',
      components: 'javascript04',
      images: 'javascript04.jpg',
      youtubeId: '',
      tags: ['javascript'],
      description:
        '리액트를 위한, 자바스크립트 기초 클래스 데이터 저장하기 파트입니다.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
    },
  ],
}

export default inputData
